server:
  servlet:
    encoding.force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  sql.init.encoding: utf-8

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
