server:
  servlet:
    encoding.force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.22:3306/grouping_test
    username: root
    password: qlqjs2ek!

  sql.init.encoding: utf-8

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
