server:
  servlet:
    encoding.force: true

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      hibernate.format-sql: true
      hibernate.default_batch_fetch_size: 100

  sql:
    init:
      mode: always
      encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/grouping_type_analysis_db
    username:
    password:
